name: Aggiornamento_Prezzi_Quotidiano

on:
  schedule:
    - cron: '0 8 * * *' # Gira ogni mattina alle 08:00 UTC
  workflow_dispatch: # Permette di farlo partire a mano per testare

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa librerie
        run: |
          pip install -r requirements.txt

      - name: Esegui lo script di scraping
        run: python monitor.py

      - name: Salva i risultati nel repository
        run: |
          git config --global user.name 'PriceBot'
          git config --global user.email 'bot@github.com'
          git add prezzi.csv
          git commit -m "Aggiornamento prezzi automatico" || exit 0
          git push
          git commit -m "Aggiornamento prezzi automatico" || exit 0
          git push
